#!/usr/bin/env python3
"""Stack the Quantum Core's two block models into one item model.

    python3 tools/build_core_item_model.py

The core is two blocks tall, so the item was showing its bottom half and
nothing else — parent: block/quantum_core_lower and that was all. A player
saw half a machine in the hotbar and in their hand.

Vanilla solves this for the bed and the chest with a BlockEntityWithoutLevel-
Renderer, which is a lot of code to draw something that never moves. It is not
needed here: block elements may run from -16 to 32 (BlockElement.MIN_EXTENT /
MAX_EXTENT), so both halves fit in one model with room to spare. The upper
half is lifted by a block, and the pair is centred on the middle of the item
box so the display transforms below need no compensating translation.

Rerun this whenever either half changes. It reads the block models, so it
cannot drift from them.
"""

import json
import os

BLOCKS = "src/main/resources/assets/quantumitems/models/block/"
OUT = "src/main/resources/assets/quantumitems/models/item/quantum_core.json"

# Vanilla block/block, scaled by 16/31 — a two-block model has to render
# smaller than a one-block one to occupy the same slot.
SHRINK = 16 / 31
DISPLAY = {
    "gui": {"rotation": [30, 225, 0], "translation": [0, 0, 0]},
    "ground": {"rotation": [0, 0, 0], "translation": [0, 3, 0]},
    "fixed": {"rotation": [0, 0, 0], "translation": [0, 0, 0]},
    "thirdperson_righthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0]},
    "thirdperson_lefthand": {"rotation": [75, 45, 0], "translation": [0, 2.5, 0]},
    "firstperson_righthand": {"rotation": [0, 45, 0], "translation": [0, 0, 0]},
    "firstperson_lefthand": {"rotation": [0, 225, 0], "translation": [0, 0, 0]},
}
BASE_SCALE = {
    "gui": 0.625, "ground": 0.25, "fixed": 0.5,
    "thirdperson_righthand": 0.375, "thirdperson_lefthand": 0.375,
    "firstperson_righthand": 0.4, "firstperson_lefthand": 0.4,
}


def lift(element, dy):
    out = dict(element)
    out["from"] = [element["from"][0], element["from"][1] + dy, element["from"][2]]
    out["to"] = [element["to"][0], element["to"][1] + dy, element["to"][2]]
    if "rotation" in element:
        origin = element["rotation"]["origin"]
        out["rotation"] = dict(element["rotation"])
        out["rotation"]["origin"] = [origin[0], origin[1] + dy, origin[2]]
    return out


def main():
    lower = json.load(open(BLOCKS + "quantum_core_lower.json"))
    upper = json.load(open(BLOCKS + "quantum_core_upper.json"))

    textures = {}
    for part in (lower, upper):
        for key, path in part["textures"].items():
            if key in textures and textures[key] != path and key != "particle":
                raise SystemExit("halves disagree on texture '%s': %s vs %s"
                                 % (key, textures[key], path))
            if key != "particle" or key not in textures:
                textures[key] = path

    # Both halves together run 0..31 in y; centre that on the item box's middle
    # so nothing has to be translated back afterwards.
    span_top = max(e["to"][1] for e in upper["elements"]) + 16
    shift = 8 - span_top / 2
    elements = ([lift(e, shift) for e in lower["elements"]]
                + [lift(e, shift + 16) for e in upper["elements"]])

    display = {}
    for context, transform in DISPLAY.items():
        scale = round(BASE_SCALE[context] * SHRINK, 4)
        display[context] = dict(transform, scale=[scale, scale, scale])

    model = {
        "__comment": "Generated by tools/build_core_item_model.py — edit the two"
                     " block models and rerun, not this file.",
        "parent": "minecraft:block/block",
        "textures": dict(sorted(textures.items())),
        "display": display,
        "elements": elements,
    }
    with open(OUT, "w") as handle:
        json.dump(model, handle, indent=2)
        handle.write("\n")
    low = min(e["from"][1] for e in elements)
    high = max(e["to"][1] for e in elements)
    print("%s: %d elements, y %.1f..%.1f, %d textures"
          % (OUT, len(elements), low, high, len(textures)))
    if low < -16 or high > 32:
        raise SystemExit("outside BlockElement's -16..32 — Minecraft will refuse this")


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    main()
